template: $CHANGES
category-template: "### $TITLE"
change-template: "- [#$NUMBER]($URL) $TITLE @$AUTHOR"
change-title-escapes: '\<&'
exclude-labels:
  - "dependencies"
  - "skip-changelog"
categories:
  - title: "ðŸ’¥ ç ´åæ€§å˜æ›´"
    labels:
      - "breaking"
  - title: "âœ¨ æ–°åŠŸèƒ½"
    labels:
      - "enhancement"
  - title: "ðŸ› é”™è¯¯ä¿®å¤"
    labels:
      - "bug"
  - title: "ðŸ’« æ‚é¡¹"
