name: 🐛 错误报告
title: "[BUG]: "
description: 创建一个错误报告来帮助我们改进
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 注意事项
        议题列表专门用于错误报告和功能需求，这意味着我们不接受使用问题。如果您打开的问题不符合要求，它将会被无条件关闭。

        有关使用问题，请通过以下方法：
        - 阅读文档以解决
        - 在社区内寻求他人解答
        - 在 discussions 上提问
        - 在网络中搜索是否有人问过类似的问题

        如果您不知道如何有效、精准地提出一个问题，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

        最后，请记得遵守我们的社区准则，要友好交流。

  - type: checkboxes
    id: terms
    attributes:
      label: 报告清单
      description: 请根据自身情况勾选。
      options:
        - label: 我已仔细阅读并了解上述注意事项。
          required: true
        - label: 我已使用最新版本测试过，确定问题依旧存在。
          required: true
        - label: 我确定此项目的议题列表中没有相同或相似的问题。
          required: true
        - label: 我确定这是此项目的问题，而不是正在使用的其他东西。
          required: true
        - label: 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

  - type: input
    id: version
    attributes:
      label: 影响版本
      description: 这个问题出现在哪个版本上？
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 请清晰简洁地说明问题是什么，并解释您是如何遇到此问题的，以及您为此做出的尝试。
      placeholder: 我遇到的问题是……
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 重现步骤
      description: |
        提供能重现此问题的详细操作步骤。如果可能，请尝试提供一个可重现的测试用例，该测试用例是发生问题所需的最低限度。
        推荐阅读：[《如何创建一个最小的、可重现的示例》](https://stackoverflow.com/help/minimal-reproducible-example)
      placeholder: |
        1. 首先……
        2. 然后……
        3. 发生……

  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 在您的预期中会发生什么？

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 实际上到底发生了什么？

  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      description: 提供有助于诊断问题的任何日志和完整的错误信息。
      placeholder: 请注意将您的敏感信息从日志中过滤或替换。

  - type: textarea
    id: context
    attributes:
      label: 额外补充
      description: 还有什么要补充的吗？在此处添加相关的任何其他上下文或截图，或者你觉得有帮助的信息。
