name: Changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: release-drafter/release-drafter@v5
      id: release-drafter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo ${{ steps.release-drafter.outputs.body }}
